# #@ load("@ytt:data", "data")
---
apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tap-overview-multi-tenant
spec:
  title: TAP Overview Multi-Tenant
  description: An introduction to the Tanzu Application Platform for Application Developers
  vendor: vmware.com
  difficulty: beginner
  duration: 100m
  url: https://github.com/dineshtripathi30/tap-workshop
  content:
    image: tanzudemoreg.azurecr.io/tapworkshop:v3
    files: github.com/Tanzu-Partner-SE/tap-workshop-1?ref=multi-tenant
    # image: #@ "harbor.{}/tanzu-e2e/inner-tap-workshop:latest".format(data.values.ingress.domain)
    # files: #@ "github.com/{}/tap-workshop?ref={}".format(data.values.git.account,data.values.git.branch)
  session:
    resources:
      memory: 3Gi
    env:
      # - name: GITEA_PASSWORD
      #   value: #@ data.values.gitea.adminPassword
      - name: VIEW_CLUSTER_DOMAIN
        value: tap11.tanzupartnerdemo.com
      - name: TAP_REGISTRY_HOST
        value: tanzudemoreg.azurecr.io
      - name: ACC_SERVER_URL
        value: https://accelerator.tap11.tanzupartnerdemo.com
      # - name: HARBOR_USER
      #   value: #@ data.values.harbor.user
      # - name: HARBOR_PASSWORD
      #   value: #@ data.values.harbor.adminPassword
    namespaces:
      budget: custom
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      registry:
        enabled: false
    objects:
      - apiVersion: v1
        kind: LimitRange
        metadata:
          name: resource-limits
        spec:
          limits:
            - type: PersistentVolumeClaim
              max:
                storage: 10Gi

      # Permissions for workshop

      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: $(session_namespace)-cluster-admin
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
          - kind: ServiceAccount
            namespace: $(workshop_namespace)
            name: $(service_account)
