apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: tap-demos
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    title: Tanzu Application Platform Demos
    password: VMware1!
    registration:
      type: anonymous
      enabled: true
    updates:
      workshop: true
    sessions:
      maximum: 10
  workshops:
    - name: tap-inner-loop-demo
      expires: 500m
      orphaned: 60m
      capacity: 20
      reserved: 2
    - name: tap-development
      expires: 60m
      orphaned: 20m
      capacity: 10
      reserved: 0
